services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mailer:
    build: .
    container_name: propspacex-mail-service
    env_file:
      - .env
    depends_on:
      - rabbitmq
    ports:
      - "9092:9092"
      - "50052:50052"
